### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by barrenechea** [halfmanbear/OpenNept4une#18]
Considering the `Stock Klipper install` thread over Discord has 3300+ messages, [GitHub Discussions](https://github.com/features/discussions) may be something to consider... Although only some people over Discord are used to GitHub, it's understandable if we don't go with it.

Either that or this project may deserve its own Discord server? 😄

**Comment by steve8x8** [comment]
I'd also vote for populating the wiki...

**Comment by halfmanbear** [comment]
Just enabled discussions and wiki
