### ISSUE TITLE
Fluidd / Klipper Calibration

### ISSUE THREAD

**Issue by michapixel** [halfmanbear/OpenNept4une#4]
is this really needed?

do we need any additional hardware? (i guess so)
Mellow Fly-ADXL345 ... any recommendations?

**Comment by halfmanbear** [comment]
yes calibration steps are recommended unless it prints perfectly as is. you can buy a Mellow Fly-ADXL345 (USB) or a standard SPI ADXL345 module

**Comment by halfmanbear** [comment]
yes has to be the A port as the type c is the serial interface only
