### ISSUE TITLE
MCU Protocol error

### ISSUE THREAD

**Issue by SrPhilippe** [halfmanbear/OpenNept4une#46]
I just went through the step-by-step installation and after finishing I got this error.

I have a NP4, V1.0 PCB version.

![image](https://github.com/halfmanbear/OpenNept4une/assets/20309766/4ec2dc95-0a2e-43fb-8ddc-ec41fcf2bc77)

**Comment by SrPhilippe** [comment]
I also followed this step and after updating the MCU the file X_4.bin changed it's name to X_4.cur which means the update was successful.
![image](https://github.com/halfmanbear/OpenNept4une/assets/20309766/e7e2a10b-09de-4fc9-a292-4116fb32a370)

**Comment by halfmanbear** [comment]
Your error is because the MCU (STM32) is showing as v0.10.0 still and not v0.12.0.
Its odd the file renamed to CUR yet didn't seem to flash the latest version.

Have you power cycled the machine since? Might be worth re-generating the .bin files and trying again to flash the MCU

**Comment by SrPhilippe** [comment]
Ok. Now my MCU is running V0.12.0 and i'm still getting the error
could this be related to RPI version, how do I update it?
![image](https://github.com/halfmanbear/OpenNept4une/assets/20309766/226973bc-cec4-43d8-b29a-523dca1448a3)

**Comment by halfmanbear** [comment]
Ok yes you need to update your Virtual MCU RPi re-run the script and select (Virtual RPi) when asked

**Comment by SrPhilippe** [comment]
> Ok yes you need to update your Virtual MCU RPi re-run the script and select (Virtual RPi) when asked

It worked out!
I was checking all MCUs update before (option 4). Now I did Virtual RPi (option 2). The error message is gone!
