### ISSUE TITLE
No Wifi Configuration

### ISSUE THREAD

**Issue by Sineiko** [halfmanbear/OpenNept4une#5]
With the new Firmware i can't make Wifi configuration

![grafik](https://github.com/halfmanbear/OpenNept4une/assets/120834220/805abbb3-67c9-4e33-900f-6de22a9372fa)

**Comment by halfmanbear** [comment]
What Printer model and PCB version do you have? Also what WiFi adapter is is?

**Comment by Sineiko** [comment]
I have the N4 Plus. I am not an expert in linux. But if you tell me what to do, then I can look it up. 

I've just come back from the night shift. I'll reply as soon as I can.

**Comment by halfmanbear** [comment]
Run this command

lsusb

Also try this then reboot after

sudo cp ~/OpenNept4une/dtb/n4plus-n4max-v1.1-2.0/rk3328-roc-cc.dtb /boot/dtb/rockchip/

**Comment by Sineiko** [comment]
Awesome. It works. Thank you.
