### ISSUE TITLE
Excited to try this!

### ISSUE THREAD

**Issue by PJMCL1618033** [halfmanbear/OpenNept4une#7]
No issue, I just want to say this is exactly what I was searching the internet to do on a Neptune 4 Pro I recently purchased. I'm new to 3D printing, so for me the Elegoo is a respectable first go at it. It seemed to me that upgrades from the manufacturer are more involved because of the custom firmware image it uses. Looking forward to De-Elegoo-ing!

**Comment by halfmanbear** [comment]
Hope you enjoy it!
